# Cooldown in seconds
Cooldown: 10

Jobs:
  - "Brewer"
  - "Chef"
  - "Doctor"
  - "Entrepreneur"
  - "Farmer"
  - "Hunter"
  - "Landscaper"
  - "LumberJack"
  - "Manufacturer"
  - "Mechanic"
  - "Pharmacist"
  - "Rancher"
  - "Realtor"
  - "TaxiDriver"
  - "TourGuide"
  - "Writer"
  - "Judge"
  - "CommunityCoordinator"
  - "Constructor"
  - "EconomySecretary"
  - "EnvironmentManager"
  - "HospitalSecretary"
  - "PoliceOfficer"
  - "Ranger"
  - "PropertyInspector"
  - "SeniorEconomySecretary"
  - "SeniorEnvironmentManager"
  - "SeniorRanger"
  - "SeniorTourGuide"
  - "Sergeant"
  - "SpeakerOfParliament"
  - "MinisterWithoutPortfolio"
  - "AgricultureMinister"
  - "ConstructionMinister"
  - "EconomyMinister"
  - "HealthMinister"
  - "JusticeMinister"
  - "PublicAffairsMinister"
  - "DeputyPrimeMinister"
  - "PrimeMinister"
  - "President"